name: Deploy BlockSight Frontend

on: [push]

jobs:
  test-and-deploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn installDependencies