name: BlockSight CI

on:
  push:
    branches: 'master'

jobs:
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [14.x]

    steps:
      - name: Install Dependencies
        - uses: actions/checkout@v1
        - run: yarn installDependencies

      # - name: Deploy
      #   uses: youyo/aws-cdk-github-actions@v1
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      #     AWS_DEFAULT_OUTPUT: ${{ secrets.AWS_DEFAULT_OUTPUT }}
      #   run: yarn deploy